platform:"ios", "6.0"

pod "UMengAnalytics"
pod "UITextView+UIControl"
pod "MKStoreKit"
pod "COSTouchVisualizer"
pod "MBProgressHUD"
pod "CRNavigationController"
pod "FontLabel"
pod "JSErrorStackTrace"
pod "JDStatusBarNotification"
pod "MLPAccessoryBadge"