git submodule add -f https://github.com/huangxinping/ShareMergeLib.git Vendor/ShareMerge
git submodule add -f https://github.com/JJMM/DurexKit.git Vendor/DurexKit
git submodule add -f https://github.com/huangxinping/GT.git Vendor/GTCore
git submodule add -f https://github.com/huangxinping/QiniuSDK.git Vendor/QiniuSDK
git submodule add -f https://github.com/huangxinping/SMMinizip.git Vendor/SMMinizip
git submodule add -f https://github.com/smileEvday/SvUDID.git Vendor/SvUDID
git submodule add -f https://github.com/huangxinping/JYTextField.git Vendor/JYTextField
git submodule add -f https://github.com/huangxinping/FocusImageView.git Vendor/FocusImageView
git submodule add -f https://github.com/beyondabel/BATableView.git Vendor/BATableView
git submodule add -f https://github.com/Dean19900504/TableViewIndex.git Vendor/TableViewIndex
git submodule add -f https://github.com/huangxinping/MJRefresh.git Vendor/MJRefresh
git submodule add -f https://github.com/mownier/MONActivityIndicatorView.git Vendor/MONActivityIndicatorView
git submodule add -f https://github.com/huangxinping/SKNavigationController.git Vendor/SKNavigationController
git submodule add -f https://github.com/huangxinping/MessagesTableViewController.git Vendor/MessagesTableViewController
git submodule add -f https://github.com/huangxinping/SWTableViewCell.git Vendor/SWTableViewCell
git submodule add -f https://github.com/huangxinping/AccessoriesComponents.git Vendor/AccessoriesComponents
git submodule add -f https://github.com/huangxinping/INSSearchBar.git Vendor/INSSearchBar
git submodule add -f https://github.com/huangxinping/Cuzy-iOS-demo.git Vendor/Cuzy
git submodule add -f https://github.com/park0ur/Path-Intro-iPhone.git Vendor/Path-Intro
git submodule add -f https://github.com/shodgin/StrikeThroughLabel.git Vendor/StrikeThroughLabel
git submodule add -f https://github.com/iOSNerd/PagedScrollView.git Vendor/PagedScrollView
git submodule add -f https://github.com/huangxinping/LayerText.git Vendor/LayerText
git submodule add -f https://github.com/huangxinping/TOWebViewController.git Vendor/TOWebViewController
git submodule add -f https://github.com/huangxinping/TMOSmarty.git Vendor/TMOSmarty
git submodule add -f https://github.com/huangxinping/MarkupLabel.git Vendor/MarkupLabel
git submodule add -f https://github.com/huangxinping/Surfboard.git Vendor/Surfboard
git submodule add -f https://github.com/huangxinping/ICETutorial.git Vendor/ICETutorial